version: '3.9'

services:
  curve-editor-server:
    image: curve-editor-server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curve-editor-server
    # restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./:/usr/src/app
